name: biopyassistant-sandbox-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scikit-learn
  - umap-learn
  - jupyterlab>=4
  - python-dotenv
  # Ploting
  - matplotlib
  - plotly
  - seaborn
  # Logging
  - loguru
  # Linters and formaters
  - pycodestyle
  - pydocstyle
  - pylint
  - black
  - ruff
  - mypy
  # LLM tools
  - chromadb # Vector storage
  - openai # For embeddings
  - black # For code formatting
  - langchain # For language processing
  - langchain-openai
  - langchain-core
  - langchain-community
  - langchain-text-splitters
  - tiktoken # For tokenization
  - transformers # For tokenization
  - pip:
    # watermark: keep track of dependency versions
    - watermark